### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by andres-erbsen** [JDLamkin/Curve-Intersect#1]
Hi,

I found your thesis when searching for follow-up work to ESolid, was pleasantly surprised by the speedups, and was thinking I would try it out and generate some figures like the ones in the paper. I read that the library can be found here, but the readme seems to be the only file in the repository. I am hoping this is not intentional?

Thanks,
Andres

**Comment by JDLamkin** [comment]
I apologize. I had not uploaded the library yet because I wanted to update
the build process to be a little more intuitive. I just didn't expect it to
be needed yet. I'll go ahead and move that up in priority and get it
uploaded by Friday.

Thanks for the interest!
Jordan Lamkin
